SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{650329A1E8EE804E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68FD1D367E6D0291}" {
     m_sEntityPrefab "{B6CD2660129A6D1C}Prefabs/Vehicles/Wheeled/Motorbike/Motorbike_US.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F486C1803290}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{5D247326389CD3ED}" {
       m_eSlotTypes 24
      }
     }
    }
    SCR_EntityCatalogEntry "{68FD1D37DD1C01F4}" {
     m_sEntityPrefab "{392A4C482678791B}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_uncovered_UA.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F486C1803290}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{5D247326389CD3ED}" {
       m_eSlotTypes 24
      }
     }
    }
    SCR_EntityCatalogEntry "{68FD1D37D9D016F7}" {
     m_sEntityPrefab "{087F248ECC1962C3}Prefabs/Vehicles/Wheeled/UAZ452/UAZ452_cargo_UA.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{62F4DEB2595BA83E}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{62F4DEB24860F6C0}" {
       m_eSlotTypes 24
      }
     }
    }
    SCR_EntityCatalogEntry "{68FD1D37989650FC}" {
     m_sEntityPrefab "{D67021EEDF78EE24}Prefabs/Vehicles/Wheeled/BRDM2/BRDM2_UA.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{62ACD28F65996D90}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{62ACD28F7AF65916}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{68FD1D37977D3F8B}" {
     m_sEntityPrefab "{8EAE2771DC651BCE}Prefabs/Vehicles/Wheeled/BTR70/BTR70_UA.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{6052F48682B04E85}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{5D247327F5578DB3}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}