SCR_MissionHeaderCampaign {
 World "{425EE07DABE5D2EC}missions/Worlds/SGC_Srhiivka.ent"
 m_sName "SolidGames Conflict in Serhiivka"
 m_sDescription "<Insert world description>"
 m_sIcon "{965B7F4AC6314189}mainmenu.edds"
 m_sLoadingScreen "{965B7F4AC6314189}mainmenu.edds"
 m_sPreviewImage "{965B7F4AC6314189}mainmenu.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}